/**
 * Content detection tests — promotional tone, readability, citeability.
 * Run: npm test or npm run test:detection
 */

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';

describe('Passive Voice Detection', () => {
  it('should detect passive constructions', () => {
    const passive = /\b(is|are|was|were|been|being)\s+(being\s+)?\w+(ed|en)\b/gi;
    const text = 'The report was generated by the system. The data is processed daily.';
    const matches = text.match(passive) || [];
    assert.ok(matches.length >= 2, `Should find passive voice (found ${matches.length})`);
  });

  it('should NOT flag adjective false positives', () => {
    const exclusions = ['interested', 'excited', 'pleased', 'concerned', 'experienced'];
    const text = 'I am interested in this topic. She is experienced in marketing.';
    // These should be excluded from passive voice count
    let falsePositives = 0;
    for (const word of exclusions) {
      if (text.includes(word)) falsePositives++;
    }
    assert.ok(falsePositives >= 2, 'Should identify common false positives for exclusion');
  });
});

describe('Answer Capsule Detection', () => {
  it('should detect 40-60 word self-contained answer blocks', () => {
    const capsule = 'AI visibility tracking measures how often and how prominently your brand or content appears in AI-generated answers from tools like ChatGPT, Perplexity, Gemini, and Google AI Overviews. Unlike traditional SEO where you track rankings, AI visibility requires tracking citations, mentions, and source attribution across multiple AI platforms.';
    const words = capsule.split(/\s+/).length;
    assert.ok(words >= 40 && words <= 70, `Capsule should be 40-70 words (got ${words})`);
  });
});

describe('Stat Attribution Quality', () => {
  it('should detect attributed stats (with source)', () => {
    const attributed = /\d+(\.\d+)?(%|\s*percent).*\(.*\d{4}\)/g;
    const text = 'AI Overviews appear in 25.11% of Google searches (Conductor, 2025).';
    const matches = text.match(attributed) || [];
    assert.ok(matches.length >= 1, 'Should detect stat with attribution');
  });

  it('should flag unattributed stats', () => {
    const text = '87% of users prefer AI search.';
    const hasAttribution = /\d+%.*\([\w\s]+,?\s*\d{4}\)/.test(text);
    assert.ok(!hasAttribution, 'Should flag stat without source attribution');
  });
});

describe('llms.txt Format Validation', () => {
  it('should validate proper llms.txt format', () => {
    const valid = '# My Site\n\n## About\n- [Home](https://example.com): Main page\n\n## Docs\n- [API](https://example.com/api): API docs\n';
    assert.ok(valid.startsWith('#'), 'Should start with # heading');
    assert.ok(/^## /m.test(valid), 'Should have ## section headings');
    assert.ok(/- \[.+\]\(.+\)/.test(valid), 'Should have markdown links');
  });

  it('should reject malformed llms.txt', () => {
    const invalid = 'Just some random text without any structure or links.';
    assert.ok(!invalid.startsWith('#'), 'Should fail: no # heading');
    assert.ok(!/^## /m.test(invalid), 'Should fail: no ## sections');
  });
});

describe('Sitemap Detection', () => {
  it('should parse XML sitemap URL count', () => {
    const xml = '<?xml version="1.0"?><urlset><url><loc>https://example.com/</loc></url><url><loc>https://example.com/about</loc></url></urlset>';
    const urlCount = (xml.match(/<loc>/g) || []).length;
    assert.equal(urlCount, 2, 'Should count 2 URLs in sitemap');
  });

  it('should detect lastmod freshness', () => {
    const recent = '<lastmod>2026-04-05</lastmod>';
    const old = '<lastmod>2025-01-01</lastmod>';
    const recentDate = new Date(recent.match(/\d{4}-\d{2}-\d{2}/)[0]);
    const oldDate = new Date(old.match(/\d{4}-\d{2}-\d{2}/)[0]);
    const now = new Date();
    const recentDays = (now - recentDate) / (1000 * 60 * 60 * 24);
    const oldDays = (now - oldDate) / (1000 * 60 * 60 * 24);
    assert.ok(recentDays < 30, 'Recent lastmod should be within 30 days');
    assert.ok(oldDays > 30, 'Old lastmod should be flagged as stale');
  });
});
